// packages/web-components/src/components/uofg-footer/link.svelte
<script lang="ts">
  import { twMerge } from 'tailwind-merge';
  import { type Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  let {
    href,
    label,
    children,
    class: className,
    ...rest
  }: {
    href: string;
    label?: string;
    class?: string;
    children: Snippet;
  } & HTMLAttributes<HTMLAnchorElement> = $props();

  const classes = twMerge(
    'w-fit underline decoration-transparent transition-colors hover:decoration-black-contrast focus:decoration-black-contrast',
    className,
  );
</script>

<a {...rest} class={classes} {href} aria-label={label ?? undefined}>
  {@render children()}
</a>

// packages/react-components/src/components/link/link.tsx
import { ComponentPropsWithoutRef, ElementType, PropsWithChildren } from 'react';
import { twMerge } from 'tailwind-merge';
import { tv } from 'tailwind-variants';

const defaultElement = 'a';

type LinkElementType = ElementType;

type LinkPropsAs<T extends LinkElementType> = {
  as?: T;
};

type LinkPropsBase = {
  href: string;
  className?: string;
};

export type LinkProps<T extends LinkElementType = typeof defaultElement> = PropsWithChildren<
  LinkPropsAs<T> & ComponentPropsWithoutRef<T> & LinkPropsBase
>;

export function Link<T extends LinkElementType = typeof defaultElement>({
  as,
  href,
  children,
  className,
  ...rest
}: LinkProps<T>) {
  const LinkComponent = as ?? defaultElement;

  const linkClasses = tv({
    base: 'text-body-copy-link underline decoration-current transition-colors hover:decoration-transparent focus:ring-2 focus-visible:ring-body-copy-link focus-visible:ring-offset-2 focus-visible:outline-none dark:text-body-copy-link-on-dark dark:focus-visible:ring-body-copy-link-on-light light:text-body-copy-link-on-light light:focus-visible:ring-body-copy-link-on-light',
  });

  return (
    <LinkComponent {...rest} href={href} className={`uofg-link ${twMerge(linkClasses(), className)}`}>
      {children}
    </LinkComponent>
  );
}

Link.displayName = 'Link';
